sugarcube-2:
  macros:
    storyletLink:
      name: storyletLink
    storyletClose:
      name: storyletClose
    storylet:
      name: storylet
    note:
      name: note
      container: true
    tabs:
      name: tabs
      container: true
    tab:
      name: tab
    requirement:
      name: requirement
    uploadMod:
      name: uploadMod
